version: '2'
services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "alexis"
      POSTGRES_PASSWORD: "alexis"
  web:
    build: .
    volumes:
      - .:/usr/local/crud
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
